apiVersion: v2
name: genieacs
description: A Helm chart for GenieACS - an open-source implementation of TR-069 ACS
type: application
version: 0.1.2
appVersion: "1.2.13.2"
keywords:
  - genieacs
  - tr-069
  - acs
  - cpe
  - device-management
home: https://genieacs.com
sources:
  - https://github.com/genieacs/genieacs
maintainers:
  - name: Sergio Fernandez
    email: acsdesk@protonmail.com
annotations:
  category: Infrastructure