blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation
    url: https://github.com/GeiserX/genieacs-docker#readme
    about: Check the README for setup instructions and configuration options
  - name: ğŸ³ Docker Hub
    url: https://hub.docker.com/r/drumsergio/genieacs
    about: Get the latest Docker image
  - name: âˆ Helm Chart
    url: https://github.com/GeiserX/genieacs-docker/tree/master/helm
    about: Kubernetes deployment with Helm
  - name: ğŸ“š Official GenieACS Wiki
    url: https://github.com/genieacs/genieacs/wiki
    about: GenieACS documentation and TR-069 configuration
